baseURL = "/kanali"
languageCode = "en-us"
title = "Kanali"
theme = "kube"
description = "Kanali is a lightweight, Kubernetes native API management gateway that together with network policies provide a robust, open source solution to Kubernetes ingress, API management, and API security."
Paginate = 4
publishDir = "../public/"
googleAnalytics = "UA-77739027-2"

[[menu.main]]
    name = "Docs"
    weight = -200
    url = "/docs/"
[[menu.main]]
    name = "Tutorial"
    weight = -100
    url = "/tutorial/"