sudo: required

language: go

matrix:
  include:
  - go: '1.10'
    env:
    - TESTS=true
    - COVERAGE=true

services:
- docker

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: kqPYySZHukKk79buA26c9staHoX7roMpp13aalARyDKoz8qdfgcCLMfBkAjI3OpIYRpqZHQlla67YBCrBgINA6ahoUm4AQF2nK7P7ll3ZM/VHwjxY6DY+wN7sSlMotBwu6qSkoCs34U8Vd1c6uCjNmDlGGgeTAY2WlLAnHNAe8FVNlYKX3fb2MOolKeLuZLh36VPbrF1409WyUFU79C20CMfN5X0sq13xOqwWJHjOaYF+wnEoOsFGt62lqGmBWXEwTOfFRKwVrYleDhR+LU0onW7k12KHydrAcI4j41mDfi0GUmLYPgCdyoffcyPNbdu6ZjmDEhF3ZSl9QXVoaSaEDIOinnbi9WJvmTRa1pE8rvB2VVz+pGB1V24aYMKZreSdkuCtFfJ1UxklW88312NcItPBVJbInY4Kqn/gMA9BwFMtzCD+pBpR06r83P3iOFs7zvzxTnuuBQ+TJUMw8PQBaRlgrDyrFY/9ORHgSGCSrquPg6nVMcxvHQoU4ugkC6fbSqnivq7TEYHTfKcUEVpLqqK+pdfB1qqCo2nAtfsViRPV2c5BXg5JyJT0uBIjukPnt7k/sJ3BOex1PAow0lgsURyy3JnRf8qAg4h28cZBBhTZCj3ovyC9TH9pcI/46EqmP7Yqs1L0UTReOG8+0cHT+d8wxECnWI8PjqN20rGWw8=
  - secure: BUFDeBBeZZ4yDuKFes7Myn1p78uYnQXnwNrgzQ48X7NBMSf5oaDL6UUH9efdiQwotF+IX8uPLU4mBabDFzZNoeb/nKEKnDMmXETjw/2x1zT1qMl3JjJbxcOM6ca3sbnOBFK4GYqgQjOR75NczVJWdZ/QsYghiPkTL+dn6nyLs7RbKXovUFu4RmM36h03R+/0LdkPPcYOa6BbAjs43BIHqsqmWDcQYs6VLVamaHQZjdVjUISP9ymK4NncXyfqDF2uRJPzitTNBwgDnkNwxBylBezrE+xIYtbGfZemVvwU6UIlQ5qHAZQgnvW8k3txmMgWg5tPxahSm0/TUUxtT32YO1aZwpjdhZmqAt0xkTQo3jJCxQS45QuTkgjaCTFXp5dZWegY+ftGWKRPTPnAVStTRephTjyBjxrPRIqNlNBOTGfMql1CE0wr/6kH3yrlx6jZbUbBEITODNG7CZ0VWxBVYRPy/EkhlaGhoAbM4HvrVpFh34ezlfK0RiWKLi4ycYAq3B78HO61UlwcZ8npMxPUkTVd4IYDPBQuGPuMEAHEYULHNn6lmKmrp2xKaBqsE2jPJH0VQqidYsH0R0osWZbNhyyxD044Yy5q+QIvLS9v1uBobyxK4hb1jkOKcWxPZX+rOPaYT8NardW3LykDPtO9IxJb/r47NtREgamuq02RzRk=

install:
- make install_ci

script:
- if [ "$TESTS" == true ]; then make unit_test; fi

after_success:
- if [ "$COVERAGE" == true ]; then make cover; fi
- if [ "$COVERAGE" == true ]; then travis_retry goveralls -coverprofile=cover.out
  -service=travis-ci || true ; else echo 'skipping coverage'; fi

notifications:
  slack:
    rooms:
      on_success: always
      on_failure: always
      secure: Z73JPNBtFixKvYaa5IFaoL+YjCh6FAMQWxS7JQje6U5ftUreDgZzsLyRLXFelqO1ScxNFvxIdoa08OZfE7/swMqwoiqCeYqwJ8goHuDs80LsOX5CBpA+9u7kyDiKFlsRhAjLFnJ/CRFvEtK4SZudD0cY0SsJszHu4dEm9KzUKbkKiYacSfgf2jNcXdC0LJoccBCG68jjbhvldUFaHUrCnyLJAhx6l1Ni2T042uo7qnfrqORPmS9Xbgkk5ibHiGSAC4BCjeP8/Oql7gx3GJizM3UIUtB8fLyj0/B/YBLrZmgf4JBqmfKHhvh7M9xw+nmz4Xpxopeox5mPs/ntBF+HZ676Dq0YZsHTo68kEygt7AzmiuITenotUftElbAtAJkLj+H1Os0gSweDDI+xLW+INT4VMbudPLhaBg30FMRe2l/R64rZzrZc9w7rQdCHg4JEoIYvbiOrMkonGvq0gFF/db2BUTDcEb8rDVMSahMot2fUiXHPA+OkpWNJ/SDdIGVN+GI5ZQQXm0L0zzg50I4cNwAuzvYAbgRQ44/IpFKKoJ9Mw5+sOJ5UbFh87OcOZccVoloaQgLGBc3OVN7C4hb7fgEQdWDIGuSMrH3Gk2jhPOYZrZh3m2Dig5gNsg8SqRInBqC+eV99FhjlTT6zzhC//IQPL47irQYyX+lyvd2XW5U=
