required = [
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/openapi-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
]

[prune]
  go-tests = true

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "v1.0.0"

[[constraint]]
  name = "github.com/opentracing/opentracing-go"
  version = "1.0.2"

[[constraint]]
  name = "github.com/uber/jaeger-client-go"
  version = "2.11.0"

[[constraint]]
  name = "github.com/uber/jaeger-lib"
  version = "v1.4.0"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.9.3"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.9.3"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.9.3"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.9.3"

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.9.3"

[[constraint]]
  name = "go.uber.org/zap"
  version = "v1.7.1"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "v1.1.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "v1.1.4"

[[constraint]]
  name = "github.com/oklog/run"
  version = "v1.0.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "v0.8.0"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "v1.4.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "v1.3.0"
